export type ExplodePart = {
  id: string;
  src: string;
  left: number;
  top: number;
  w: number;
  h: number;
  x: number;
  y: number;
  rotate: number;
  z: number;
  boost?: boolean;
};

export const EXPLODE_CAR = "/explode/car.png?v=6";

export const EXPLODE_PARTS: ExplodePart[] = [
  {
    id: "hood",
    src: "/explode/hood.png?v=4",
    left: 3,
    top: 41,
    w: 32,
    h: 13.5,
    x: -90,
    y: -240,
    rotate: -28,
    z: 14,
  },
  {
    id: "engine",
    src: "/explode/engine.png?v=4",
    left: 10,
    top: 36,
    w: 17,
    h: 22,
    x: -20,
    y: -310,
    rotate: 8,
    z: 16,
    boost: true,
  },
  {
    id: "gearbox",
    src: "/explode/gearbox.png?v=4",
    left: 22,
    top: 44,
    w: 14,
    h: 16,
    x: 30,
    y: 150,
    rotate: 12,
    z: 15,
    boost: true,
  },
  {
    id: "turbo",
    src: "/explode/turbo.png?v=4",
    left: 15,
    top: 40,
    w: 10,
    h: 10,
    x: -120,
    y: -170,
    rotate: -18,
    z: 15,
  },
  {
    id: "radiator",
    src: "/explode/radiator.png?v=4",
    left: 5,
    top: 42,
    w: 11,
    h: 13,
    x: -210,
    y: 10,
    rotate: -8,
    z: 14,
  },
  {
    id: "battery",
    src: "/explode/battery.png?v=4",
    left: 19,
    top: 38,
    w: 8,
    h: 10,
    x: -90,
    y: -150,
    rotate: 10,
    z: 14,
  },
  {
    id: "bumper",
    src: "/explode/bumper.png?v=4",
    left: 2.8,
    top: 48,
    w: 14,
    h: 16,
    x: -230,
    y: 50,
    rotate: -10,
    z: 13,
  },
  {
    id: "headlight",
    src: "/explode/headlight.png?v=4",
    left: 3,
    top: 47,
    w: 8,
    h: 8,
    x: -200,
    y: -40,
    rotate: -6,
    z: 13,
  },
  {
    id: "fender",
    src: "/explode/fender.png?v=4",
    left: 3,
    top: 42,
    w: 32,
    h: 24,
    x: -200,
    y: -30,
    rotate: -12,
    z: 8,
  },
  {
    id: "front-wheel",
    src: "/explode/wheel.png?v=4",
    left: 14.8,
    top: 51.2,
    w: 12.8,
    h: 19.2,
    x: -190,
    y: 160,
    rotate: 160,
    z: 16,
  },
  {
    id: "front-suspension",
    src: "/explode/suspension.png?v=4",
    left: 17,
    top: 52,
    w: 7,
    h: 16,
    x: -140,
    y: 140,
    rotate: 16,
    z: 7,
  },
  {
    id: "door",
    src: "/explode/door.png?v=4",
    left: 33.5,
    top: 30.4,
    w: 21.5,
    h: 35.4,
    x: 40,
    y: -200,
    rotate: 14,
    z: 10,
  },
  {
    id: "rear-door",
    src: "/explode/rear-door.png?v=4",
    left: 53.5,
    top: 30.2,
    w: 19.5,
    h: 35.6,
    x: 80,
    y: -190,
    rotate: -10,
    z: 10,
  },
  {
    id: "roof",
    src: "/explode/roof.png?v=4",
    left: 35,
    top: 29.5,
    w: 49,
    h: 13,
    x: 10,
    y: -290,
    rotate: -3,
    z: 12,
  },
  {
    id: "seat",
    src: "/explode/seat.png?v=4",
    left: 38,
    top: 32,
    w: 9,
    h: 22,
    x: 20,
    y: -210,
    rotate: -6,
    z: 9,
  },
  {
    id: "skirt",
    src: "/explode/skirt.png?v=4",
    left: 32,
    top: 62,
    w: 40,
    h: 4.5,
    x: 0,
    y: 130,
    rotate: 2,
    z: 6,
  },
  {
    id: "quarter",
    src: "/explode/quarter.png?v=4",
    left: 70,
    top: 30.5,
    w: 27,
    h: 39.5,
    x: 210,
    y: 20,
    rotate: 12,
    z: 8,
  },
  {
    id: "trunk",
    src: "/explode/trunk.png?v=4",
    left: 74,
    top: 33,
    w: 23,
    h: 22,
    x: 190,
    y: -120,
    rotate: 14,
    z: 9,
  },
  {
    id: "taillight",
    src: "/explode/taillight.png?v=4",
    left: 90,
    top: 46,
    w: 7,
    h: 8,
    x: 220,
    y: -50,
    rotate: 8,
    z: 13,
  },
  {
    id: "rear-wheel",
    src: "/explode/wheel.png?v=4",
    left: 71.2,
    top: 51.2,
    w: 12.8,
    h: 19.2,
    x: 200,
    y: 160,
    rotate: -160,
    z: 16,
  },
  {
    id: "rear-suspension",
    src: "/explode/suspension.png?v=4",
    left: 72,
    top: 52,
    w: 7,
    h: 16,
    x: 150,
    y: 140,
    rotate: -16,
    z: 7,
  },
  {
    id: "rear-bumper",
    src: "/explode/rear-bumper.png?v=4",
    left: 85,
    top: 51,
    w: 12,
    h: 13,
    x: 230,
    y: 50,
    rotate: 10,
    z: 12,
  },
  {
    id: "exhaust",
    src: "/explode/exhaust.png?v=4",
    left: 54,
    top: 61,
    w: 22,
    h: 6,
    x: 90,
    y: 120,
    rotate: 8,
    z: 5,
  },
  {
    id: "chassis",
    src: "/explode/chassis.png?v=4",
    left: 3,
    top: 32,
    w: 93,
    h: 38,
    x: 0,
    y: 70,
    rotate: 0,
    z: 2,
  },
];

export function clamp01(n: number) {
  return Math.max(0, Math.min(1, n));
}

export function explodeProgress(p: number) {
  return clamp01((p - 0.1) / 0.86);
}

export function explodeTransform(t: number, part: ExplodePart, k: number) {
  const eased = Math.pow(t, 1.85);
  const scale = part.boost ? 0.82 + 0.32 * eased : 1 + 0.06 * eased;
  return `translate(${part.x * eased * k}px, ${part.y * eased * k}px) rotate(${part.rotate * eased}deg) scale(${scale})`;
}
